pandoc -t beamer -o slidespython.pdf slidespython.md
pandoc -t beamer -o streamlit.pdf streamlit.md
pandoc -t beamer -o slidesnumpy.pdf numpy.md
pandoc -t beamer -o scipy.pdf scipy.md
pandoc -t beamer -o slidesmatplotlib.pdf slidesmatplotlib.md
pandoc -t beamer -o algebra.pdf algebra.md
pandoc -t beamer -o linearregression.pdf linearregression.md
pandoc -t beamer -o analyse.pdf analyse.md
pandoc -t beamer -o sandsynlighedsteori.pdf sandsynlighedsteori.md
pandoc -t beamer -o logistiskregression.pdf logistiskregression.md
pandoc -t beamer -o deskriptiv.pdf deskriptivstatistik.md
